builds:
  - binary: acme-dns
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: tgz
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - Dockerfile
      - config.cfg
      - acme-dns.service

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
  - image_templates:
    - "joohoi/acme-dns:{{ .Tag }}"
    - "joohoi/acme-dns:latest"
    dockerfile: Dockerfile.release
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.url={{.GitURL}}"
