builds:
  - binary: acme-dns
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: tgz
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - Dockerfile
      - config.cfg
      - acme-dns.service

signs:
  - artifacts: checksum
