builds:
  - binary: acme-dns
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - 386
      - amd64

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
    - Dockerfile
    - config.cfg
