apiVersion: v1
kind: Service
metadata:
  name: {{ include "acmedns.fullname" . }}-dns
  labels:
    {{- include "acmedns.labels" . | nindent 4 }}
  {{- with .Values.serviceDNS.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
spec:
  type: {{ .Values.serviceDNS.type }}
  ports:
    - port: 53
      targetPort: tcp-dns
      protocol: TCP
      name: tcp-dns
    - port: 53
      targetPort: udp-dns
      protocol: UDP
      name: udp-dns      
  selector:
    {{- include "acmedns.selectorLabels" . | nindent 4 }}
