name: golangci-lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
